version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-247-209.compute-1.amazonaws.com
            database: d8j5cugamokp3q
            ssl: true
            user: uzyttcprppfufq
            password: 4c68b5fe889d7703d49ba9501e00ac5ed735fbd31712e4565c49634776639274
            rawAccess: true
            port: '5432'
            migrations: true